### ISSUE TITLE
Add Bert Frees to the workshop pariticipants team

### ISSUE THREAD

**Issue by rdeltour** [xproc/Workshop-2018-02#1]
Can you please add @bertfrees to the team?

Bert is a DAISY staff member, and co-lead of our XProc-based "DAISY Pipeline" project.

ping @ndw @gimsieke @xml-project

**Comment by xml-project** [comment]
Done (some what of)!

**Comment by rdeltour** [comment]
Thanks Achim for giving Bert write access to the wiki!
Maybe this issue can be left open until he's properly added to the team, for (potentially) future workshops?

**Comment by xml-project** [comment]
Yes, it was wrong to close it.
@ndw

**Comment by ndw** [comment]
@bertfrees if you accept the invitation that was sent a while back (I think there will be a link on the xproc page if you just go there), you'll be in the workshop team.

**Comment by bertfrees** [comment]
Thanks.
