### ISSUE TITLE
Tuesday evening dinner option

### ISSUE THREAD

**Issue by Gertone** [xproc/Workshop-2018-02#3]
http://www.restaurace-lavicka.cz/en/

**Comment by ndw** [comment]
Meet at 19:00? Bethan and I will plan to be there.

**Comment by sgmlguru** [comment]
Sounds good to me.

**Comment by dmj** [comment]
+1

**Comment by mkraetke** [comment]
+1

**Comment by xatapult** [comment]
+1

 

Van: Norman Walsh [mailto:notifications@github.com] 
Verzonden: dinsdag 6 februari 2018 16:15
Aan: xproc/Workshop-2018-02 <Workshop-2018-02@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [xproc/Workshop-2018-02] Tuesday evening dinner option (#3)

 

Meet at 19:00? Bethan and I will plan to be there.

**Comment by Gertone** [comment]
Me too

**Comment by xml-project** [comment]
DONE!
